### ISSUE TITLE
utime/stime conversion on linux?

### ISSUE THREAD

**Issue by jason-o-matic** [djberg96/proc-wait3#4]
I've been playing around with a few different methods for getting process info and I noticed a mismatch between what I was getting from this gem's `wait4` call and what was in `/proc/PID/stat` (after converting from jiffys to seconds).

This caused me to check out the source, particularly:
https://github.com/djberg96/proc-wait3/blob/master/ext/proc/wait3.c#L259
where I saw `INT2FIX(r.ru_utime.tv_sec + (r.ru_utime.tv_usec/1000.0))`.

I would expect `tv_usec` to be divided by 1 million since it's microseconds, instead of 1 thousand. I'm not super familiar with the rusage struct (having only checked out http://linux.die.net/man/2/getrusage) so I could be missing something?

**Comment by djberg96** [comment]
Isn't tv_usec milliseconds?

**Comment by jason-o-matic** [comment]
"u" usually stands for micro, but I did a little googling just to verify.

http://linux.die.net/man/2/gettimeofday
http://www.gnu.org/software/libc/manual/html_node/Elapsed-Time.html

Both of those list tv_usec as microseconds:
```
struct timeval {
    time_t      tv_sec;     /* seconds */
    suseconds_t tv_usec;    /* microseconds */
};
```

**Comment by djberg96** [comment]
You're right, and I use 1e6 elsewhere, so I just spaced out there. Nice catch.

I've pushed out 1.7.3. Thanks for the report!
